// These are all the valid query parameters when searching for a page
// Note that there is another type of pagination, which is seperate because pagination is generated by the server if required

interface IPageQueryParams {
	name?: RegExp;
	// this is how mongoose stores nested objects for queries
	"meta.template"?: string;
}

export default IPageQueryParams;
